### ISSUE TITLE
Error running loadModel

### ISSUE THREAD

**Issue by andrewwself** [ShapeNet/shapenet-viewer#27]
Hi,

I am getting the following error when running loadModel on a ply file saved locally on my computer:

14:35:37.356 [pool-1-thread-1] ERROR e.s.g.shapenet.jme3.viewer.Viewer - Error running loadModel
org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at https://www.shapenet.org/solr/models3d: Expected mime type application/octet-stream but got application/json. {"error":"proxy_error","reason":"connect ECONNREFUSED 127.0.0.1:8498"}
	at org.apache.solr.client.solrj.impl.HttpSolrClient.executeMethod(HttpSolrClient.java:528) ~[shapenet-viewer-assembly-0.1.0.jar:0.1.0]
	at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:234) ~[shapenet-viewer-assembly-0.1.0.jar:0.1.0]
	at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:226) ~[shapenet-viewer-assembly-0.1.0.jar:0.1.0]
	at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:135) ~[shapenet-viewer-assembly-0.1.0.jar:0.1.0]
	at org.apache.solr.client.solrj.SolrClient.query(SolrClient.java:943) ~[shapenet-viewer-assembly-0.1.0.jar:0.1.0]
	at org.apache.solr.client.solrj.SolrClient.query(SolrClient.java:958) ~[shapenet-viewer-assembly-0.1.0.jar:0.1.0]
	at edu.stanford.graphics.shapenet.data.SolrQuerier.getModelInfo(SolrQuerier.scala:146) ~[shapenet-viewer-assembly-0.1.0.jar:0.1.0]
	at edu.stanford.graphics.shapenet.data.DataManager.getModelInfoFromSolr(DataManager.scala:23) ~[shapenet-viewer-assembly-0.1.0.jar:0.1.0]
	at edu.stanford.graphics.shapenet.data.DataManager.getModelInfo(DataManager.scala:31) ~[shapenet-viewer-assembly-0.1.0.jar:0.1.0]
	at edu.stanford.graphics.shapenet.jme3.loaders.AssetLoader.loadModelAsScene(AssetLoader.scala:67) ~[shapenet-viewer-assembly-0.1.0.jar:0.1.0]
	at edu.stanford.graphics.shapenet.jme3.Jme.loadModelAsScene(Jme.scala:94) ~[shapenet-viewer-assembly-0.1.0.jar:0.1.0]
	at edu.stanford.graphics.shapenet.jme3.viewer.Viewer$$anon$6.run(Viewer.scala:691) ~[shapenet-viewer-assembly-0.1.0.jar:0.1.0]
	at edu.stanford.graphics.shapenet.util.RunnableWithLogging.run(Threads.scala:20) ~[shapenet-viewer-assembly-0.1.0.jar:0.1.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_191]

The program was working for me just a couple of days ago and I did not change anything about how I was running it when I started getting the error. This seems like the same error as #8: https://github.com/ShapeNet/shapenet-viewer/issues/8. Thank you for your help!

**Comment by Raven1996** [comment]
Same error. They try to load model from the Internet, but URL is not reliable.

**Comment by jadrs** [comment]
I'm having the same issue. In my case, when using the viewer to generate renders using a custom .conf file. The problem also happens using batch-render-example.conf, so I think this is not a problem ofo my script. What I get is:

13:10:44.040 [pool-1-thread-1] ERROR e.s.g.shapenet.jme3.viewer.Viewer - Error running loadModel
org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at https://www.shapenet.org/solr/models3d: Expected mime type application/octet-stream but got application/json. {"error":"proxy_error","reason":"connect ECONNREFUSED 127.0.0.1:8498"}
	at org.apache.solr.client.solrj.impl.HttpSolrClient.executeMethod(HttpSolrClient.java:528) ~[shapenet-viewer-assembly-0.1.0.jar:0.1.0]
	at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:234) ~[shapenet-viewer-assembly-0.1.0.jar:0.1.0]
	at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:226) ~[shapenet-viewer-assembly-0.1.0.jar:0.1.0]
	at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:135) ~[shapenet-viewer-assembly-0.1.0.jar:0.1.0]
	at org.apache.solr.client.solrj.SolrClient.query(SolrClient.java:943) ~[shapenet-viewer-assembly-0.1.0.jar:0.1.0]
	at org.apache.solr.client.solrj.SolrClient.query(SolrClient.java:958) ~[shapenet-viewer-assembly-0.1.0.jar:0.1.0]
	at edu.stanford.graphics.shapenet.data.SolrQuerier.getModelInfo(SolrQuerier.scala:146) ~[shapenet-viewer-assembly-0.1.0.jar:0.1.0]
	at edu.stanford.graphics.shapenet.data.DataManager.getModelInfoFromSolr(DataManager.scala:23) ~[shapenet-viewer-assembly-0.1.0.jar:0.1.0]
	at edu.stanford.graphics.shapenet.data.DataManager.getModelInfo(DataManager.scala:31) ~[shapenet-viewer-assembly-0.1.0.jar:0.1.0]
	at edu.stanford.graphics.shapenet.jme3.loaders.AssetLoader.loadModelAsScene(AssetLoader.scala:67) ~[shapenet-viewer-assembly-0.1.0.jar:0.1.0]
	at edu.stanford.graphics.shapenet.jme3.Jme.loadModelAsScene(Jme.scala:94) ~[shapenet-viewer-assembly-0.1.0.jar:0.1.0]
	at edu.stanford.graphics.shapenet.jme3.viewer.Viewer$$anon$6.run(Viewer.scala:691) ~[shapenet-viewer-assembly-0.1.0.jar:0.1.0]
	at edu.stanford.graphics.shapenet.util.RunnableWithLogging.run(Threads.scala:20) ~[shapenet-viewer-assembly-0.1.0.jar:0.1.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_191]

**Comment by luojiapeng14** [comment]
I got the similar error when load model. I have download the Corev2 data and register the local path by using the register command. But it's weired that it still tried to connect to remote servers.
