### ISSUE TITLE
viewer.sh freezes ?

### ISSUE THREAD

**Issue by aOlmo** [ShapeNet/shapenet-viewer#31]
I have installed shapenet-viewer and followed the steps given in the README and when I try to run ./scripts/viewer.sh to start the viewer, it freezes. 
The red progress bar doesn't move and shows:
`Loading model: 3dw.111cb08cbc8121b8411749672386e0b711`

I am getting the following error which depicts there is a URL not working. Note that I have changed it to be https://www.shapenet.org/solr/#/models3d as pointed in #8 but still does not work:

> ERROR e.s.g.shapenet.jme3.viewer.Viewer - Error running loadModel
org.apache.solr.client.solrj.SolrServerException: IOException occured when talking to server at: https://www.shapenet.org/solr/#/models3d
	at org.apache.solr.client.solrj.impl.HttpSolrClient.executeMethod(HttpSolrClient.java:574) ~[shapenet-viewer-assembly-0.1.0.jar:0.1.0]
	at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:234) ~[shapenet-viewer-assembly-0.1.0.jar:0.1.0]
	at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:226) ~[shapenet-viewer-assembly-0.1.0.jar:0.1.0]
	at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:135) ~[shapenet-viewer-assembly-0.1.0.jar:0.1.0]
	at org.apache.solr.client.solrj.SolrClient.query(SolrClient.java:943) ~[shapenet-viewer-assembly-0.1.0.jar:0.1.0]
	at org.apache.solr.client.solrj.SolrClient.query(SolrClient.java:958) ~[shapenet-viewer-assembly-0.1.0.jar:0.1.0]
	at edu.stanford.graphics.shapenet.data.SolrQuerier.getModelInfo(SolrQuerier.scala:146) ~[shapenet-viewer-assembly-0.1.0.jar:0.1.0]
	at edu.stanford.graphics.shapenet.data.DataManager.getModelInfoFromSolr(DataManager.scala:23) ~[shapenet-viewer-assembly-0.1.0.jar:0.1.0]
	at edu.stanford.graphics.shapenet.data.DataManager.getModelInfo(DataManager.scala:31) ~[shapenet-viewer-assembly-0.1.0.jar:0.1.0]
	at edu.stanford.graphics.shapenet.jme3.loaders.AssetLoader.loadModelAsScene(AssetLoader.scala:67) ~[shapenet-viewer-assembly-0.1.0.jar:0.1.0]
	at edu.stanford.graphics.shapenet.jme3.Jme.loadModelAsScene(Jme.scala:94) ~[shapenet-viewer-assembly-0.1.0.jar:0.1.0]
	at edu.stanford.graphics.shapenet.jme3.viewer.Viewer$$anon$6.run(Viewer.scala:691) ~[shapenet-viewer-assembly-0.1.0.jar:0.1.0]
	at edu.stanford.graphics.shapenet.util.RunnableWithLogging.run(Threads.scala:20) ~[shapenet-viewer-assembly-0.1.0.jar:0.1.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_222]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_222]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_222]
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192) ~[na:1.8.0_222]
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1946) ~[na:1.8.0_222]
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:316) ~[na:1.8.0_222]
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:310) ~[na:1.8.0_222]
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1639) ~[na:1.8.0_222]
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:223) ~[na:1.8.0_222]
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1037) ~[na:1.8.0_222]
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:965) ~[na:1.8.0_222]
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1064) ~[na:1.8.0_222]
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367) ~[na:1.8.0_222]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395) ~[na:1.8.0_222]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379) ~[na:1.8.0_222]
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:543) ~[shapenet-viewer-assembly-0.1.0.jar:0.1.0]
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:409) ~[shapenet-viewer-assembly-0.1.0.jar:0.1.0]
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177) ~[shapenet-viewer-assembly-0.1.0.jar:0.1.0]
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:304) ~[shapenet-viewer-assembly-0.1.0.jar:0.1.0]
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611) ~[shapenet-viewer-assembly-0.1.0.jar:0.1.0]
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446) ~[shapenet-viewer-assembly-0.1.0.jar:0.1.0]
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:882) ~[shapenet-viewer-assembly-0.1.0.jar:0.1.0]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[shapenet-viewer-assembly-0.1.0.jar:0.1.0]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107) ~[shapenet-viewer-assembly-0.1.0.jar:0.1.0]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55) ~[shapenet-viewer-assembly-0.1.0.jar:0.1.0]
	at org.apache.solr.client.solrj.impl.HttpSolrClient.executeMethod(HttpSolrClient.java:465) ~[shapenet-viewer-assembly-0.1.0.jar:0.1.0]
	... 17 common frames omitted
Caused by: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
	at sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:362) ~[na:1.8.0_222]
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:259) ~[na:1.8.0_222]
	at sun.security.validator.Validator.validate(Validator.java:262) ~[na:1.8.0_222]
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:330) ~[na:1.8.0_222]
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:237) ~[na:1.8.0_222]
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132) ~[na:1.8.0_222]
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1621) ~[na:1.8.0_222]
	... 35 common frames omitted
Caused by: java.security.cert.CertPathValidatorException: validity check failed
	at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:135) ~[na:1.8.0_222]
	at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:233) ~[na:1.8.0_222]
	at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:141) ~[na:1.8.0_222]
	at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:80) ~[na:1.8.0_222]
	at java.security.cert.CertPathValidator.validate(CertPathValidator.java:292) ~[na:1.8.0_222]
	at sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:357) ~[na:1.8.0_222]
	... 41 common frames omitted
Caused by: java.security.cert.CertificateExpiredException: NotAfter: Tue Apr 23 05:00:00 MST 2019
	at sun.security.x509.CertificateValidity.valid(CertificateValidity.java:274) ~[na:1.8.0_222]
	at sun.security.x509.X509CertImpl.checkValidity(X509CertImpl.java:629) ~[na:1.8.0_222]
	at sun.security.provider.certpath.BasicChecker.verifyValidity(BasicChecker.java:190) ~[na:1.8.0_222]
	at sun.security.provider.certpath.BasicChecker.check(BasicChecker.java:144) ~[na:1.8.0_222]
	at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125) ~[na:1.8.0_222]
	... 46 common frames omitted

**Comment by nsievers** [comment]
Can confirm, I am getting the same issues.  I can run commands from the console like registering the shapeNetCore path, which it does say:

_'Opening ~/ShapeNetCore.v2/taxonomy.json'_  

But when I try to load a model it says that:

_[jME3 Main] WARN  e.s.g.shapenet.jme3.viewer.Viewer - Loading already in progress...._

That's it, no loading, blank white screen.

**Comment by dclcs** [comment]
I have the same problem, do you solve this problem?

**Comment by LeiJiang1** [comment]
same as me

**Comment by apple2373** [comment]
I have the same problem.
