### ISSUE TITLE
Error running loadModel on Startup

### ISSUE THREAD

**Issue by nlunscher** [ShapeNet/shapenet-viewer#8]
Hi

When I run the viewer I get stuck at the screen showing the progress bar with "Loading model: 3dw.111cb08c8121b8411749672386e0b711"

In terminal it shows the below error. Am I missing something? Is the URL it is trying to access out of date?

Thanks in advance for your help!

Error in Terminal:
18:31:39.101 [pool-1-thread-1] ERROR e.s.g.shapenet.jme3.viewer.Viewer - Error running loadModel
org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://shapenet.cs.stanford.edu/models3d/solr: Expected mime type application/octet-stream but got text/html. <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /models3d/solr/select was not found on this server.</p>
<hr>
<address>Apache/2.2.22 (Ubuntu) Server at shapenet.cs.stanford.edu Port 80</address>
</body></html>

	at org.apache.solr.client.solrj.impl.HttpSolrClient.executeMethod(HttpSolrClient.java:528) ~[shapenet-viewer-assembly-0.1.0.jar:0.1.0]
	at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:234) ~[shapenet-viewer-assembly-0.1.0.jar:0.1.0]
	at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:226) ~[shapenet-viewer-assembly-0.1.0.jar:0.1.0]
	at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:135) ~[shapenet-viewer-assembly-0.1.0.jar:0.1.0]
	at org.apache.solr.client.solrj.SolrClient.query(SolrClient.java:943) ~[shapenet-viewer-assembly-0.1.0.jar:0.1.0]
	at org.apache.solr.client.solrj.SolrClient.query(SolrClient.java:958) ~[shapenet-viewer-assembly-0.1.0.jar:0.1.0]
	at edu.stanford.graphics.shapenet.data.SolrQuerier.getModelInfo(SolrQuerier.scala:146) ~[shapenet-viewer-assembly-0.1.0.jar:0.1.0]
	at edu.stanford.graphics.shapenet.data.DataManager.getModelInfoFromSolr(DataManager.scala:23) ~[shapenet-viewer-assembly-0.1.0.jar:0.1.0]
	at edu.stanford.graphics.shapenet.data.DataManager.getModelInfo(DataManager.scala:31) ~[shapenet-viewer-assembly-0.1.0.jar:0.1.0]
	at edu.stanford.graphics.shapenet.jme3.loaders.AssetLoader.loadModelAsScene(AssetLoader.scala:67) ~[shapenet-viewer-assembly-0.1.0.jar:0.1.0]
	at edu.stanford.graphics.shapenet.jme3.Jme.loadModelAsScene(Jme.scala:94) ~[shapenet-viewer-assembly-0.1.0.jar:0.1.0]
	at edu.stanford.graphics.shapenet.jme3.viewer.Viewer$$anon$6.run(Viewer.scala:687) ~[shapenet-viewer-assembly-0.1.0.jar:0.1.0]
	at edu.stanford.graphics.shapenet.util.RunnableWithLogging.run(Threads.scala:20) ~[shapenet-viewer-assembly-0.1.0.jar:0.1.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]

**Comment by msavva** [comment]
Thank you for reporting this issue -- there was indeed an out of date URL in the code.  This should be fixed now.

**Comment by nlunscher** [comment]
Great Thanks! I can confirm it works now.

**Comment by Univerfly** [comment]
Is the current URL out of date again?

```
10:44:41.016 [pool-1-thread-1] ERROR e.s.g.shapenet.jme3.viewer.Viewer - Error running
 loadModel                                                                            
org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from serve
r at http://www.shapenet.org/solr/models3d: Expected mime type application/octet-strea
m but got text/html. <html>                                                           
<head>                                                                                
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>                  
<title>Error 404 Not Found</title>                                                    
</head>                                                                               
<body><h2>HTTP ERROR 404</h2>                                                         
<p>Problem accessing /solr/models3d/select. Reason:                                   
<pre>    Not Found</pre></p><hr><i><small>Powered by Jetty://</small></i><hr/>        
                                                                                      
</body>                                                                               
</html>                            
```

**Comment by Po0ria** [comment]
I get the same error it seems that this is the new link but I don't know where should I change it:
https://www.shapenet.org/solr/#/models3d
